version: '3.5'

services:

  traefik:
    image: jahrik/arm-traefik:aarch64
    # command: --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/g1/traefik/acme.json:/etc/traefik/acme.json
    environment:
      CF_API_EMAIL: "${CF_API_EMAIL}"
      CF_API_KEY: "${CF_API_KEY}"
    ports:
      - 8082:8080
      - 80:80
    networks:
      - traefik
    deploy:
      # mode: replicated
      # replicas: 1
      labels:
        traefik.enable: 1
        traefik.port: 8080
        traefik.backend: traefik
        traefik.docker.network: traefik
        traefik.frontend.rule: Host:traefik.homelab.business
      placement:
        constraints:
          - node.role == manager
          - node.labels.arch == aarch64

networks:
  traefik:
    name: traefik
    driver: overlay
