FROM jahrik/arm-gosu-tini:armv7l

ADD https://github.com/containous/traefik/releases/download/v1.7.4/traefik_linux-arm /traefik
RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get -y install \
      ca-certificates \
      curl \
      wget \
      htop \
      iputils-ping \
      net-tools \
      dnsutils \
 && chmod +x /traefik

COPY traefik.toml /etc/traefik/traefik.toml

EXPOSE 80 8080 443
ENTRYPOINT ["/traefik"]
