version: '3.5'

services:

  traefik:
    image: jahrik/arm-traefik:aarch64
    command:
      - "--api"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/g1/traefik/acme.json:/etc/traefik/acme.json
    ports:
      - 8082:8080
      - 80:80
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.arch == aarch64

  ghost:
    image: arm64v8/ghost
    ports:
      - 8083:2368
    networks:
      - traefik
    deploy:
      replicas: 2
      labels:
        traefik.enable: 1
        traefik.docker.network: traefik
        traefik.backend: ghost
        traefik.port: 2368
        traefik.frontend.rule: Host:ghost.homelab.business
        traefik.frontend.entryPoints: http
      placement:
        constraints:
          - node.labels.arch == aarch64

networks:
  traefik:
    name: traefik
    driver: overlay
