############
# Defaults #
############
debug = false
logLevel = "INFO"
[api]
  entryPoint = "traefik"
  dashboard = true
  # usersFile = /etc/traefik/.htpasswd

########
# HTTP #
########

# defaultEntryPoints = ["http"]
# 
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
# 
# [docker]
# endpoint = "unix:///var/run/docker.sock"
# # domain = "homelab.business"
# watch = true
# swarmMode = true
# network = "traefik"
# exposedByDefault = false

############################
# Docker and let's encrypt #
############################

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
 
[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "homelab.business"
  swarmMode = true
  watch = true
  network = "traefik"
  exposedByDefault = false

[acme]
  email = "jahrik@gmail.com"
  storage = "/etc/traefik/acme.json"
  entryPoint = "https"
  onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

###############################
# On host with http challenge #
###############################

# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]
# 
# [docker]
#   endpoint = "unix:///var/run/docker.sock"
#   domain = "homelab.business"
#   watch = true
#   swarmMode = true
#   network = "traefik"
#   exposedByDefault = false
# 
# [acme]
#   email = "jahrik@gmail.com"
#   storage = "/etc/traefik/acme.json"
#   onHostRule = true
#   caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#   entryPoint = "https"
# 
# [acme.httpChallenge]
#   entryPoint = "http"
#  
# [[acme.domains]]
#   main = "homelab.business"
#   sans = ["homelab.business"]

##############
# Cloudflare #
##############

# defaultEntryPoints = ["https","http"]

# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]

# [docker]
#   endpoint = "unix:///var/run/docker.sock"
#   domain = "homelab.business"
#   watch = true
#   swarmMode = true
#   network = "traefik"
#   exposedByDefault = false
# 
# [acme]
#   email = "jahrik@gmail.com"
#   storage = "/etc/traefik/acme.json"
#   caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#   entryPoint = "https"
# 
# [acme.dnsChallenge]
#   provider = "cloudflare"
#   delayBeforeCheck = 0
# 
# [[acme.domains]]
#   main = "*.homelab.business"
#   sans = ["homelab.business"]

###########
# Metrics #
###########
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]
