debug = false
logLevel = "INFO"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "homelab.business"
watch = true
swarmMode = true
network = "traefik"
exposedByDefault = false

[acme]
email = "jahrik@gmail.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
onHostRule = true
dnsProvider = "cloudflare"
[[acme.domains]]
  main = "*.homelab.business"
[acme.httpChallenge]
entryPoint = "http"
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
